In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import os
os.getcwd()
import pandas as pd

df = pd.read_csv(r"C:\Users\Sirushtika S\OneDrive\Desktop\weekly task\archive (1).zip")
print("Dataset loaded successfully")

Dataset loaded successfully

In [4]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [5]:
# First 5 rows
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [6]:
#last rows 5
df.tail()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [7]:
df.sample()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
44419,CHrIStINa BAKeR,55,Male,A+,Diabetes,2024-03-29,Lee Allen,Wilson-Adams,Blue Cross,34473.662132,339,Elective,2024-04-10,Ibuprofen,Abnormal

In [8]:
df.shape

(55500, 15)

In [9]:
df.columns

Index(['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition',
       'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider',
       'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date',
       'Medication', 'Test Results'],
      dtype='object')

In [10]:
df.dtypes

Name                   object
Age                     int64
Gender                 object
Blood Type             object
Medical Condition      object
Date of Admission      object
Doctor                 object
Hospital               object
Insurance Provider     object
Billing Amount        float64
Room Number             int64
Admission Type         object
Discharge Date         object
Medication             object
Test Results           object
dtype: object

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

In [12]:
df.describe()

                Age  Billing Amount   Room Number
count  55500.000000    55500.000000  55500.000000
mean      51.539459    25539.316097    301.134829
std       19.602454    14211.454431    115.243069
min       13.000000    -2008.492140    101.000000
25%       35.000000    13241.224652    202.000000
50%       52.000000    25538.069376    302.000000
75%       68.000000    37820.508436    401.000000
max       89.000000    52764.276736    500.000000

In [13]:
df.isnull()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55496,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55497,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55498,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55499,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [14]:
df.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [15]:
df.dropna()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [16]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
55495    False
55496    False
55497    False
55498    False
55499    False
Length: 55500, dtype: bool

In [17]:
df.duplicated().sum()

np.int64(534)

In [18]:
df.drop_duplicates()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [19]:
df["Date of Admission"] = pd.to_datetime(df["Date of Admission"])
print(df)

                    Name  Age  Gender Blood Type Medical Condition  \
0          Bobby JacksOn   30    Male         B-            Cancer
1           LesLie TErRy   62    Male         A+           Obesity
2            DaNnY sMitH   76  Female         A-           Obesity
3           andrEw waTtS   28  Female         O+          Diabetes
4          adrIENNE bEll   43  Female        AB+            Cancer
...                  ...  ...     ...        ...               ...
55495  eLIZABeTH jaCkSOn   42  Female         O+            Asthma
55496         KYle pEREz   61  Female        AB-           Obesity
55497       HEATher WaNG   38  Female         B+      Hypertension
55498     JENniFER JOneS   43    Male         O-         Arthritis
55499       jAMES GARCiA   53  Female         O+         Arthritis

      Date of Admission            Doctor                      Hospital  \
0            2024-01-31     Matthew Smith               Sons and Miller
1            2019-08-20   Samantha Davies                       Kim Inc
2            2022-09-22  Tiffany Mitchell                      Cook PLC
3            2020-11-18       Kevin Wells    Hernandez Rogers and Vang,
4            2022-09-19    Kathleen Hanna                   White-White
...                 ...               ...                           ...
55495        2020-08-16     Joshua Jarvis                Jones-Thompson
55496        2020-01-23   Taylor Sullivan                  Tucker-Moyer
55497        2020-07-13    Joe Jacobs DVM  and Mahoney Johnson Vasquez,
55498        2019-05-25    Kimberly Curry      Jackson Todd and Castro,
55499        2024-04-02     Dennis Warren                Henry Sons and

      Insurance Provider  Billing Amount  Room Number Admission Type  \
0             Blue Cross    18856.281306          328         Urgent
1               Medicare    33643.327287          265      Emergency
2                  Aetna    27955.096079          205      Emergency
3               Medicare    37909.782410          450       Elective
4                  Aetna    14238.317814          458         Urgent
...                  ...             ...          ...            ...
55495         Blue Cross     2650.714952          417       Elective
55496              Cigna    31457.797307          316       Elective
55497   UnitedHealthcare    27620.764717          347         Urgent
55498           Medicare    32451.092358          321       Elective
55499              Aetna     4010.134172          448         Urgent

      Discharge Date   Medication  Test Results
0         2024-02-02  Paracetamol        Normal
1         2019-08-26    Ibuprofen  Inconclusive
2         2022-10-07      Aspirin        Normal
3         2020-12-18    Ibuprofen      Abnormal
4         2022-10-09   Penicillin      Abnormal
...              ...          ...           ...
55495     2020-09-15   Penicillin      Abnormal
55496     2020-02-01      Aspirin        Normal
55497     2020-08-10    Ibuprofen      Abnormal
55498     2019-05-31    Ibuprofen      Abnormal
55499     2024-04-29    Ibuprofen      Abnormal

[55500 rows x 15 columns]

In [20]:
df["Age"] = pd.to_numeric(df["Age"])
print(df)

                    Name  Age  Gender Blood Type Medical Condition  \
0          Bobby JacksOn   30    Male         B-            Cancer
1           LesLie TErRy   62    Male         A+           Obesity
2            DaNnY sMitH   76  Female         A-           Obesity
3           andrEw waTtS   28  Female         O+          Diabetes
4          adrIENNE bEll   43  Female        AB+            Cancer
...                  ...  ...     ...        ...               ...
55495  eLIZABeTH jaCkSOn   42  Female         O+            Asthma
55496         KYle pEREz   61  Female        AB-           Obesity
55497       HEATher WaNG   38  Female         B+      Hypertension
55498     JENniFER JOneS   43    Male         O-         Arthritis
55499       jAMES GARCiA   53  Female         O+         Arthritis

      Date of Admission            Doctor                      Hospital  \
0            2024-01-31     Matthew Smith               Sons and Miller
1            2019-08-20   Samantha Davies                       Kim Inc
2            2022-09-22  Tiffany Mitchell                      Cook PLC
3            2020-11-18       Kevin Wells    Hernandez Rogers and Vang,
4            2022-09-19    Kathleen Hanna                   White-White
...                 ...               ...                           ...
55495        2020-08-16     Joshua Jarvis                Jones-Thompson
55496        2020-01-23   Taylor Sullivan                  Tucker-Moyer
55497        2020-07-13    Joe Jacobs DVM  and Mahoney Johnson Vasquez,
55498        2019-05-25    Kimberly Curry      Jackson Todd and Castro,
55499        2024-04-02     Dennis Warren                Henry Sons and

      Insurance Provider  Billing Amount  Room Number Admission Type  \
0             Blue Cross    18856.281306          328         Urgent
1               Medicare    33643.327287          265      Emergency
2                  Aetna    27955.096079          205      Emergency
3               Medicare    37909.782410          450       Elective
4                  Aetna    14238.317814          458         Urgent
...                  ...             ...          ...            ...
55495         Blue Cross     2650.714952          417       Elective
55496              Cigna    31457.797307          316       Elective
55497   UnitedHealthcare    27620.764717          347         Urgent
55498           Medicare    32451.092358          321       Elective
55499              Aetna     4010.134172          448         Urgent

      Discharge Date   Medication  Test Results
0         2024-02-02  Paracetamol        Normal
1         2019-08-26    Ibuprofen  Inconclusive
2         2022-10-07      Aspirin        Normal
3         2020-12-18    Ibuprofen      Abnormal
4         2022-10-09   Penicillin      Abnormal
...              ...          ...           ...
55495     2020-09-15   Penicillin      Abnormal
55496     2020-02-01      Aspirin        Normal
55497     2020-08-10    Ibuprofen      Abnormal
55498     2019-05-31    Ibuprofen      Abnormal
55499     2024-04-29    Ibuprofen      Abnormal

[55500 rows x 15 columns]

In [21]:
# Unique Gender Values
df["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [22]:
 #Unique Medical Conditions
df["Medical Condition"].unique()

array(['Cancer', 'Obesity', 'Diabetes', 'Asthma', 'Hypertension',
       'Arthritis'], dtype=object)

In [23]:
# Unique Admission Types
df["Admission Type"].unique()

array(['Urgent', 'Emergency', 'Elective'], dtype=object)

In [24]:
# Frequency of Medical Conditions
df["Medical Condition"].value_counts()

Medical Condition
Arthritis       9308
Diabetes        9304
Hypertension    9245
Obesity         9231
Cancer          9227
Asthma          9185
Name: count, dtype: int64

In [25]:
#  Frequency of Admission Types
df["Admission Type"].value_counts()

Admission Type
Elective     18655
Urgent       18576
Emergency    18269
Name: count, dtype: int64

In [26]:
df.groupby("Medical Condition")["Billing Amount"].mean()

Medical Condition
Arthritis       25497.327056
Asthma          25635.249359
Cancer          25161.792707
Diabetes        25638.405577
Hypertension    25497.095761
Obesity         25805.971259
Name: Billing Amount, dtype: float64

In [27]:
df.groupby("Medical Condition")["Billing Amount"].agg(
    ["mean","median","min","max","std"]
)

,mean,median,min,max,std
Medical Condition,,,,,
Arthritis,25497.327056,25581.763549,-1129.997176,52170.036854,14276.529904
Asthma,25635.249359,25661.872824,-1520.420555,52181.837792,14241.677464
Cancer,25161.792707,24910.980640,-2008.492140,52373.032374,14200.271700
Diabetes,25638.405577,25621.077269,-1316.618581,52211.852966,14159.524315
Hypertension,25497.095761,25275.670593,-1660.009373,52764.276736,14305.400942
Obesity,25805.971259,26129.997134,-1310.272895,52024.726443,14079.526507

In [28]:
df["Age"].std()

19.602453808513932

In [29]:
df["Age"].quantile([0.25,0.50,0.75])

0.25    35.0
0.50    52.0
0.75    68.0
Name: Age, dtype: float64

In [30]:
df["Gender"] = df["Gender"].str.strip()
df["Medical Condition"] = df["Medical Condition"].str.strip()
df["Admission Type"] = df["Admission Type"].str.strip()
df["Insurance Provider"] = df["Insurance Provider"].str.strip()

In [31]:
df["Gender"] = df["Gender"].str.title()
df["Medical Condition"] = df["Medical Condition"].str.title()
df["Admission Type"] = df["Admission Type"].str.title()
df["Insurance Provider"] = df["Insurance Provider"].str.title()

In [32]:
print(df["Gender"].unique())
print(df["Medical Condition"].unique())
print(df["Admission Type"].unique())
print(df["Insurance Provider"].unique())

['Male' 'Female']
['Cancer' 'Obesity' 'Diabetes' 'Asthma' 'Hypertension' 'Arthritis']
['Urgent' 'Emergency' 'Elective']
['Blue Cross' 'Medicare' 'Aetna' 'Unitedhealthcare' 'Cigna']

In [33]:
df[
    (df["Age"]>60)&
    (df["Admission Type"] =="Emergency")
    ]

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
12,connOR HANsEn,75,Female,A+,Diabetes,2019-12-12,Kenneth Fletcher,"Powers Miller, and Flores",Cigna,43282.283358,134,Emergency,2019-12-28,Penicillin,Abnormal
24,PAUl hEndERsOn,72,Female,AB+,Hypertension,2020-05-15,Stephanie Kramer,Wilson Group,Medicare,33211.295419,109,Emergency,2020-06-08,Paracetamol,Inconclusive
38,NIcOlE LUcErO,70,Female,O-,Diabetes,2022-03-12,Christine Johnson,"and Garcia Morris Cunningham,",Cigna,48290.693407,113,Emergency,2022-03-29,Lipitor,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55467,SaNDrA ChEN,62,Female,B+,Asthma,2022-06-03,Morgan Hess,Park Ltd,Aetna,48563.608920,269,Emergency,2022-06-06,Lipitor,Abnormal
55471,iaN MuRpHy,73,Female,B+,Hypertension,2023-05-03,Leslie Guerra,Lozano Ltd,Aetna,28397.377193,348,Emergency,2023-05-06,Lipitor,Abnormal
55487,mIsTy RICharDs,78,Female,O-,Hypertension,2024-04-10,Sarah Dyer,Garcia-Wells,Cigna,34150.133741,409,Emergency,2024-04-23,Ibuprofen,Normal
55490,STepHAniE oliVer,82,Male,B-,Cancer,2022-01-10,Gary Leblanc,Group Lee,Cigna,17350.543524,381,Emergency,2022-01-21,Penicillin,Abnormal
55494,JEssIcA WHiTe,67,Male,O+,Arthritis,2023-12-11,Jesus Jordan,Miller-Harris,Medicare,42535.301234,378,Emergency,2024-01-04,Ibuprofen,Normal

In [34]:
df[(df["Gender"] == "Female") & (df["Medical Condition"] == "Diabetes")]

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
6,edwArD EDWaRDs,21,Female,AB-,Diabetes,2020-11-03,Kelly Olson,Group Middleton,Medicare,19580.872345,389,Emergency,2020-11-15,Paracetamol,Inconclusive
12,connOR HANsEn,75,Female,A+,Diabetes,2019-12-12,Kenneth Fletcher,"Powers Miller, and Flores",Cigna,43282.283358,134,Emergency,2019-12-28,Penicillin,Abnormal
27,mr. KenNEth MoORE,34,Female,A+,Diabetes,2022-06-21,James Ellis,Serrano-Dixon,Unitedhealthcare,18834.801341,157,Emergency,2022-06-30,Lipitor,Abnormal
34,NicOlE RodriGUEz,30,Female,AB+,Diabetes,2020-01-17,Lynn Young,Poole Inc,Blue Cross,8408.949354,285,Emergency,2020-02-10,Lipitor,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55408,laura lOPEz,56,Female,O+,Diabetes,2022-02-27,Tyler Williamson,Smith-Butler,Blue Cross,5828.981010,421,Emergency,2022-03-23,Aspirin,Abnormal
55420,SteVeN knoX,52,Female,A-,Diabetes,2023-08-12,Alicia Garcia,Molina-Phelps,Unitedhealthcare,5271.154491,379,Elective,2023-08-24,Ibuprofen,Inconclusive
55433,RonALd OBRIeN jr.,72,Female,B+,Diabetes,2019-11-16,John Singh,"Hunter and Mckenzie, Parsons",Aetna,13959.491185,462,Urgent,2019-12-06,Lipitor,Abnormal
55462,alYSsA mIlLER,35,Female,A-,Diabetes,2022-06-30,Ryan Price,Shelton-Gallagher,Unitedhealthcare,2210.460898,289,Elective,2022-07-27,Penicillin,Normal
55480,LAurEn mills,33,Female,B-,Diabetes,2020-09-30,Mr. David Murray MD,"Riggs, King and Walls",Cigna,22375.523434,323,Emergency,2020-10-26,Aspirin,Abnormal

In [35]:
df[(df["Age"] < 30) & (df["Admission Type"] == "Elective")]

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
35,DAvID AndErSON,25,Female,AB+,Asthma,2021-01-07,Emma Allison,Sons and Cox,Medicare,45453.418546,228,Elective,2021-01-26,Lipitor,Abnormal
53,PeGGY LEe,24,Female,A-,Obesity,2022-04-08,Patrick Burns,"Nelson Walker Myers, and",Unitedhealthcare,6767.634397,180,Elective,2022-04-13,Lipitor,Abnormal
63,LArry rodgeRs,23,Female,B-,Hypertension,2022-08-03,Eric Kelly,"and Mason Smith Chase,",Cigna,5517.393642,113,Elective,2022-08-10,Aspirin,Inconclusive
67,jOhN hARTmAN,27,Male,B-,Hypertension,2023-01-07,Jack Jackson,Bullock-Ramsey,Cigna,49402.298373,263,Elective,2023-01-27,Lipitor,Inconclusive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55313,mIRanDA ROsE,28,Female,AB-,Asthma,2024-03-21,Jonathan Barker,Drake Inc,Blue Cross,44983.299910,222,Elective,2024-04-15,Penicillin,Normal
55315,DAviD KiM,26,Male,O+,Asthma,2023-05-08,Jeremy Carney,"Miller, Rodriguez and Robinson",Unitedhealthcare,10654.730649,404,Elective,2023-05-24,Lipitor,Abnormal
55362,ChRISTinA wrighT,27,Female,O-,Obesity,2019-08-21,Juan Mueller MD,Jacobs Ltd,Aetna,26482.785254,389,Elective,2019-09-15,Ibuprofen,Inconclusive
55459,Mark RiVEra,25,Male,B-,Arthritis,2019-08-14,Debra Randolph MD,"Hughes, and Cunningham Sanchez",Cigna,2078.470454,143,Elective,2019-09-07,Aspirin,Abnormal
55483,kimbErlY RIchArDSoN,15,Male,A-,Diabetes,2022-06-27,Erik Jones,PLC Hill,Blue Cross,12239.838237,177,Elective,2022-07-05,Lipitor,Abnormal

In [36]:
df[(df["Billing Amount"] > 40000) & (df["Gender"] == "Male")]

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
5,EMILY JOHNSOn,36,Male,A+,Asthma,2023-12-20,Taylor Newton,Nunez-Humphrey,Unitedhealthcare,48145.110951,389,Urgent,2023-12-24,Ibuprofen,Normal
8,JASmINe aGuIlaR,82,Male,AB+,Asthma,2020-07-01,Daniel Ferguson,Sons Rich and,Cigna,50119.222792,316,Elective,2020-07-14,Aspirin,Abnormal
30,ThOMAS MartInEZ,34,Male,B-,Asthma,2019-08-18,Jacob Huynh,Hart Ltd,Cigna,47909.128810,371,Urgent,2019-09-01,Ibuprofen,Inconclusive
45,lYNn MaRtinez,65,Male,O+,Cancer,2022-10-12,Daniel Murphy,Group Armstrong,Medicare,45585.886560,300,Emergency,2022-11-02,Penicillin,Normal
62,tRAvIs carTeR,18,Male,A+,Cancer,2022-07-06,Megan Hahn,"Moss and Ferguson, Baker",Unitedhealthcare,48407.386291,325,Emergency,2022-07-18,Aspirin,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55456,DEBRa MIller,17,Male,AB-,Cancer,2021-07-29,Samantha Russell,Collier-Jordan,Unitedhealthcare,43230.028453,125,Urgent,2021-08-01,Ibuprofen,Abnormal
55470,TaYLOr bEST,60,Male,A-,Asthma,2020-10-14,Tracy Nichols,"Hopkins and Neal Logan,",Cigna,48664.879041,187,Emergency,2020-10-21,Penicillin,Normal
55484,keNNEtH alvarez,80,Male,O+,Cancer,2022-05-05,Andrew Conner,Sons Mayo and,Cigna,45653.802310,114,Elective,2022-05-17,Aspirin,Normal
55489,ANdrEw AGUIlaR,69,Male,O-,Arthritis,2019-06-25,Dustin Pearson,"and Barry White, Jones",Medicare,41893.245150,171,Urgent,2019-07-09,Paracetamol,Normal
55494,JEssIcA WHiTe,67,Male,O+,Arthritis,2023-12-11,Jesus Jordan,Miller-Harris,Medicare,42535.301234,378,Emergency,2024-01-04,Ibuprofen,Normal

In [37]:
df[(df["Medical Condition"] == "Cancer") & (df["Blood Type"] == "A+")]

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
7,CHrisTInA MARtinez,20,Female,A+,Cancer,2021-12-28,Suzanne Thomas,"Powell Robinson and Valdez,",Cigna,45820.462722,277,Emergency,2022-01-07,Paracetamol,Inconclusive
56,beThaNY MoOrE,55,Female,A+,Cancer,2023-04-09,Penny Pruitt,"and Montes Graves, Thomas",Cigna,10300.657311,330,Emergency,2023-04-21,Paracetamol,Normal
62,tRAvIs carTeR,18,Male,A+,Cancer,2022-07-06,Megan Hahn,"Moss and Ferguson, Baker",Unitedhealthcare,48407.386291,325,Emergency,2022-07-18,Aspirin,Normal
88,wILLIAM hIlL,38,Female,A+,Cancer,2023-05-16,Matthew Walker,Lindsey Inc,Cigna,39476.947514,428,Elective,2023-06-01,Aspirin,Abnormal
237,larRy MaYEr,25,Female,A+,Cancer,2023-12-07,Richard Petty,Miller PLC,Blue Cross,36990.455775,356,Urgent,2023-12-14,Aspirin,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55068,MR. RichArD GreEn,83,Male,A+,Cancer,2021-04-18,Angelica Stewart,Bailey-Jones,Medicare,41237.172596,395,Elective,2021-05-07,Aspirin,Inconclusive
55120,LAuReN WIlSoN,57,Female,A+,Cancer,2021-06-18,Philip Jackson,Horton PLC,Blue Cross,12195.291621,389,Emergency,2021-07-07,Ibuprofen,Normal
55155,ScOtt WRigHt,82,Male,A+,Cancer,2019-09-29,Heather Williams,"and Reyes Phillips, Miller",Blue Cross,20961.880359,159,Emergency,2019-10-22,Penicillin,Normal
55250,cheLSeA FrENCh,20,Male,A+,Cancer,2020-11-10,Rachel Rose,Johnson-Chavez,Unitedhealthcare,5877.265250,248,Emergency,2020-11-19,Ibuprofen,Inconclusive
55389,tiFfAnY FErguSON,82,Female,A+,Cancer,2022-09-10,Eric Lutz,Johnson Group,Blue Cross,27971.280361,120,Emergency,2022-09-14,Lipitor,Abnormal

In [38]:
df[(df["Billing Amount"] >= 20000) & (df["Billing Amount"] <= 30000)]

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
16,haley perkins,63,Female,A+,Arthritis,2020-06-23,Erica Spencer,Cervantes-Wells,Unitedhealthcare,24499.847904,114,Elective,2020-07-14,Paracetamol,Normal
19,dANIEL schmIdt,63,Male,B+,Asthma,2022-11-15,Denise Galloway,Hammond Ltd,Cigna,23762.203579,465,Elective,2022-11-22,Penicillin,Normal
23,dR. EilEEn thomPsoN,59,Male,A+,Asthma,2021-08-02,Donna Martinez MD,and Sons Smith,Aetna,25250.052428,119,Urgent,2021-08-12,Lipitor,Inconclusive
26,cathy sMaLl,51,Female,O-,Asthma,2023-12-23,Wendy Glenn,"Brown, and Jones Weaver",Blue Cross,26786.529555,401,Elective,2024-01-19,Ibuprofen,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55471,iaN MuRpHy,73,Female,B+,Hypertension,2023-05-03,Leslie Guerra,Lozano Ltd,Aetna,28397.377193,348,Emergency,2023-05-06,Lipitor,Abnormal
55475,darrEn andREws,34,Female,A+,Hypertension,2023-12-19,Alexandria Merritt,"Hubbard, Garza Jordan and",Blue Cross,25548.318105,127,Emergency,2023-12-25,Paracetamol,Inconclusive
55480,LAurEn mills,33,Female,B-,Diabetes,2020-09-30,Mr. David Murray MD,"Riggs, King and Walls",Cigna,22375.523434,323,Emergency,2020-10-26,Aspirin,Abnormal
55481,deboRaH pEARsOn,34,Male,A+,Obesity,2022-01-05,David Williams,Stone-Stout,Blue Cross,25051.501373,144,Elective,2022-02-04,Paracetamol,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",Unitedhealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal

In [39]:
df.sort_values("Billing Amount" , ascending=False)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
36349,tOdd CARrILlO,51,Female,A+,Hypertension,2023-09-08,Kathleen Griffin,Griffin Group,Blue Cross,52764.276736,209,Elective,2023-10-04,Ibuprofen,Normal
51313,kARen klInE,74,Female,AB+,Cancer,2021-06-19,Dr. Joseph Gordon,Hernandez-Morton,Unitedhealthcare,52373.032374,181,Urgent,2021-07-03,Penicillin,Inconclusive
34613,kARen klInE,79,Female,AB+,Cancer,2021-06-19,Dr. Joseph Gordon,Hernandez-Morton,Unitedhealthcare,52373.032374,181,Urgent,2021-07-03,Penicillin,Inconclusive
5735,DAVId SanDOvaL,22,Male,AB-,Hypertension,2019-11-02,Taylor Novak,Sons and Bailey,Blue Cross,52271.663747,228,Emergency,2019-11-11,Ibuprofen,Normal
7088,kathRYN GoNzales,18,Female,O+,Diabetes,2020-08-11,Kristin Clark,Miller Ltd,Aetna,52211.852966,383,Urgent,2020-08-12,Paracetamol,Inconclusive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29484,tErRy WILSOn,39,Male,O-,Diabetes,2024-02-19,Diana Smith,"Medina and Elliott Stewart,",Aetna,-1316.618581,491,Emergency,2024-03-20,Paracetamol,Inconclusive
44040,JOsEPH robBins,71,Male,O-,Hypertension,2024-02-10,Stacey Davenport,Vaughn PLC,Unitedhealthcare,-1428.843941,205,Urgent,2024-02-29,Ibuprofen,Abnormal
42621,joHn hahN,80,Male,O-,Asthma,2024-02-24,Mark Hines,Ltd Wilson,Cigna,-1520.420555,403,Elective,2024-03-14,Lipitor,Abnormal
48659,EMMA savAGE,57,Male,AB+,Hypertension,2021-09-05,Maria Johnson,Armstrong LLC,Blue Cross,-1660.009373,193,Elective,2021-10-02,Penicillin,Normal
47589,james lUnA,64,Female,AB-,Cancer,2022-09-22,Todd Becker,Juarez-Clark,Aetna,-2008.492140,162,Urgent,2022-10-20,Ibuprofen,Abnormal

In [40]:
condition_summary = (
    df.groupby("Medical Condition")["Billing Amount"]
    .mean()
    .reset_index()
)

condition_summary

  Medical Condition  Billing Amount
0         Arthritis    25497.327056
1            Asthma    25635.249359
2            Cancer    25161.792707
3          Diabetes    25638.405577
4      Hypertension    25497.095761
5           Obesity    25805.971259

In [41]:
df[["Age", "Billing Amount", "Room Number"]].corr()

                     Age  Billing Amount  Room Number
Age             1.000000       -0.003832    -0.000720
Billing Amount -0.003832        1.000000    -0.002943
Room Number    -0.000720       -0.002943     1.000000

In [42]:
df["Length of Stay"] = (
    pd.to_datetime(df["Discharge Date"]) - 
    pd.to_datetime(df["Date of Admission"])
).dt.days

df[["Date of Admission", "Discharge Date", "Length of Stay"]].head()

  Date of Admission Discharge Date  Length of Stay
0        2024-01-31     2024-02-02               2
1        2019-08-20     2019-08-26               6
2        2022-09-22     2022-10-07              15
3        2020-11-18     2020-12-18              30
4        2022-09-19     2022-10-09              20

In [43]:
df["Admission Year"] = pd.to_datetime(
    df["Date of Admission"]
).dt.year

df[["Date of Admission", "Admission Year"]].head()

  Date of Admission  Admission Year
0        2024-01-31            2024
1        2019-08-20            2019
2        2022-09-22            2022
3        2020-11-18            2020
4        2022-09-19            2022

In [47]:
df["Admission Month"] = pd.to_datetime(
    df["Date of Admission"]
).dt.month

df[["Date of Admission", "Admission Month"]].head()

  Date of Admission  Admission Month
0        2024-01-31                1
1        2019-08-20                8
2        2022-09-22                9
3        2020-11-18               11
4        2022-09-19                9

In [48]:
df.groupby("Admission Year")["Billing Amount"].mean()

Admission Year
2019    25700.463671
2020    25392.254250
2021    25629.483239
2022    25513.509808
2023    25573.848469
2024    25380.295013
Name: Billing Amount, dtype: float64

In [49]:
monthly_admissions = (
    df.groupby("Admission Month")["Name"]
    .count()
    .reset_index()
)

monthly_admissions

    Admission Month  Name
0                 1  4692
1                 2  4255
2                 3  4672
3                 4  4518
4                 5  4599
5                 6  4699
6                 7  4812
7                 8  4832
8                 9  4546
9                10  4678
10               11  4548
11               12  4649

In [ ]:
=